# Generated by Django 4.1 on 2024-01-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcategory_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
    ]
