# Generated by Django 4.1 on 2024-01-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='تایید شده/نشده'),
        ),
    ]
