# Generated by Django 4.1 on 2024-01-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productcomment_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='confirmation',
            field=models.BooleanField(default=True, verbose_name='تایید شده/نشده'),
        ),
    ]
