# Generated by Django 4.1 on 2024-02-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productcomment_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='Score',
            field=models.IntegerField(default=1, verbose_name='امتیاز به محصول'),
        ),
    ]
