# Generated by Django 4.1 on 2024-02-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productcomment_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productcolor', verbose_name=' رنگ محصول'),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productsize', verbose_name=' سایز محصول'),
        ),
    ]
