# Generated by Django 4.1 on 2024-02-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productsizegallery_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSizeGallery',
        ),
    ]
