# Generated by Django 4.1 on 2024-02-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productfavorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productfavorite',
            options={'verbose_name': 'علاقه مندی محصول', 'verbose_name_plural': 'علاقه مندی های محصولات'},
        ),
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='نام محصول'),
        ),
    ]
