# Generated by Django 4.1 on 2024-02-10 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_productfavorite_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfavorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='نام محصول'),
        ),
    ]
