# Generated by Django 4.1 on 2024-02-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productfavorite_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductFavorite',
        ),
    ]
