# Generated by Django 4.1 on 2024-02-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_productwishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='Score',
            new_name='score',
        ),
    ]
