# Generated by Django 4.1 on 2024-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_rename_score_productcomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='score',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='امتیاز به محصول'),
        ),
    ]
