# Generated by Django 4.1 on 2024-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_productcomment_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomment',
            name='score',
            field=models.IntegerField(default=5, verbose_name='امتیاز به محصول'),
        ),
    ]
