# Generated by Django 4.1 on 2024-02-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_newslettersubscriber_newslettersubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='user',
        ),
    ]
