# Generated by Django 4.1 on 2024-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
