# Generated by Django 4.1 on 2024-01-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0004_menulinkbox_menulink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulinkbox',
            name='url',
        ),
    ]
