# Generated by Django 4.1 on 2024-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0005_remove_menulinkbox_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='header_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن سایت'),
        ),
    ]
