# Generated by Django 4.1 on 2024-02-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0007_questioncommongroup_questioncommon'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncommon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال / غیرفعال'),
        ),
    ]
