# Generated by Django 4.1 on 2024-02-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0008_questioncommon_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncommon',
            name='question_common_group',
        ),
        migrations.AddField(
            model_name='questioncommon',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionCommonGroup',
        ),
    ]
