# Generated by Django 4.1 on 2024-02-21 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0010_alter_questioncommon_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCommonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی سوالات متداول',
                'verbose_name_plural': 'دسته بندی های سوالات متداول',
            },
        ),
        migrations.RemoveField(
            model_name='questioncommon',
            name='title',
        ),
        migrations.AddField(
            model_name='questioncommon',
            name='question_common_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='site_setting.questioncommongroup', verbose_name='دسته بندی'),
        ),
    ]
